[package]
name = "zwei_bot"
version = "0.1.0"
edition = "2021"
authors = ["RivenSkaye <riven@tae.moe>"]
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.9"
serde = "^1.0.100"
serde_json = "1.0.70"
lazy_static = "1.4.0"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[profile.release]
opt-level = 2
debug = 0
debug-assertions = false
overflow-checks = true
lto = true
incremental = true
codegen-units = 96

[profile.release.build-override]
opt-level = 2
codegen-units = 96
