[package]
name = "zwei_bot"
version = "0.1.0"
edition = "2021"
authors = ["RivenSkaye <riven@tae.moe>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.10.9"

[profile.release]
opt-level = 2
debug = 0
debug-assertions = false
overflow-checks = true
lto = true
incremental = true
codegen-units = 96

[profile.release.build-override]
opt-level = 2
codegen-units = 96
