name: Codeberg Sync

on:
  schedule: [{cron: "18 */4 * * *"}]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: github2berg
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/RivenSkaye/ZweiBot.git'
          GIT_USERNAME: RivenSkaye
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      - name: berg2github
        uses: bridgelightcloud/github-mirror-action@v1
        with:
          origin: 'https://codeberg.org/RivenSkaye/ZweiBot.git'
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
